apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}