apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb-chart.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.service.metallbAddressPool }}
    metallb.universe.tf/address-pool: {{ .Values.service.metallbAddressPool | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: 27017
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
    app.kubernetes.io/component: haproxy