apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mongodb-chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mongodb-chart.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "mongodb-chart.name" . }}
        app.kubernetes.io/component: database
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        # BasePath is "templates", so don't repeat "templates/" again:
        # checksum/auth-secret: {{ include (print $.Template.BasePath "/secret-auth.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "mongodb-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      # --- init: copy secret file into an emptyDir with strict perms/owner
      initContainers:
        - name: prepare-keyfile
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              install -m 400 -o 999 -g 999 /secret/keyfile /work/keyfile
          volumeMounts:
            - name: keyfile-secret
              mountPath: /secret
              readOnly: true
            - name: keydir
              mountPath: /work

      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["mongod"]
          args:
            - "--bind_ip_all"
            - "--replSet={{ .Values.replicaSet.name }}"
            - "--auth"
            - "--keyFile=/etc/mongo-keyfile/keyfile"
          ports:
            - name: mongodb
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.auth.existingSecret }}{{ .Values.auth.existingSecret }}{{ else }}{{ include "mongodb-chart.fullname" . }}-auth{{ end }}
                  key: MONGODB_ROOT_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.auth.existingSecret }}{{ .Values.auth.existingSecret }}{{ else }}{{ include "mongodb-chart.fullname" . }}-auth{{ end }}
                  key: MONGODB_ROOT_PASSWORD
          volumeMounts:
            - name: datadir
              mountPath: /data/db
            - name: configdir
              mountPath: /data/configdb
            - name: keydir                    # ← mount prepared file dir
              mountPath: /etc/mongo-keyfile
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  mongo --quiet --eval 'db.adminCommand("ping")' || mongosh --quiet --eval 'db.adminCommand("ping")'
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

      volumes:
        - name: configdir
          emptyDir: {}
        {{- if not .Values.persistence.enabled }}
        - name: datadir
          emptyDir: {}
        {{- end }}
        - name: keyfile-secret
          secret:
            secretName: {{ if .Values.auth.existingSecret }}{{ .Values.auth.existingSecret }}{{ else }}{{ include "mongodb-chart.fullname" . }}-auth{{ end }}
            items:
              - key: KEYFILE_CONTENT
                path: keyfile
            defaultMode: 0400
        - name: keydir
          emptyDir: {}